
# .github/keyword.yml
 
# Label for bug-related changes
bug:
    - bug
    - fix
enhancement:                            # Label for feature-related changes
    - new
    - feat
duplicate:                         # Label for duplicate issues
    - duplicate
good first issue:
    - initial 
