
# .github/labeler.yml
 
# Label for bug-related changes
bug:
    - '(bug|fix)'
enhancement:                            # Label for feature-related changes
    - '(feature|new)'
documentation:                         # Label for doc-related changes
    - '(docs|documentation)'