name: Auto-Labelling of Issues
on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Labels
        uses: actions/issue-labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
