name: Auto-Labelling of Issues
 
on:
  issues:
    types: [opened, reopened]
 
permissions:
  issues: write
  contents: read
 
jobs:
  Labelling:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.3 
      with:
        configuration-path: .github/labeler.yml
        not-before: 2024-11-22T02:00:00Z
        enable-versioned-regex: 0
        repo-token: ${{ github.token }}
