name: Auto-Labelling of Issues
 
on:
  issues:
    types: [opened]
 
permissions:
  issues: write
 
jobs:
  AutoLabelling:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.3 
      with:
        configuration-path: .github/keyword.yml
        not-before: 2024-11-22T02:00:00Z
         repo-token: ${{ github.token }}
